version: "3.8"

services:
  app:
    image: chat-back:local
    container_name: chat-back
    restart: on-failure
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3500"
      - "3005:3005"
    depends_on:
      - db_chat
      - rabbitmq
    links:
        - rabbitmq
        - db_chat
    volumes:
      - .:/app

  db_chat:
    container_name: pg_container_chat
    image: postgres:alpine
    restart: on-failure
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: lang_ex
    ports:
      - "5432:5432"
    volumes:
      - ./db_data:/var/lib/postgresql/data/

  pgadmin_chat:
    container_name: pgadmin4_container_chat
    image: dpage/pgadmin4
    restart: on-failure
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: root
    ports:
      - "5050:80"

  rabbitmq:
    container_name: rabbitmq
    image: rabbitmq:3.9-management
    restart: on-failure
    hostname: rabbitmq
    volumes:
      - /var/lib/rabbitmq
      - ./rabbitmq.conf:/etc/rabbitmq/rabbitmq.conf
    ports:
      - "5672:5672"
      - "15672:15672"